version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  app:
    container_name: app
    # restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: .env
    volumes:
      - ./:/home/node/app/
      - ./nodemon.json:/home/node/app/src/nodemon.json
    environment:
      - PORT=${PORT}
      - SECRET=${SECRET}
      - DB_HOST=${DB_HOST}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
    networks:
      - postgres
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: npm run dev

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    app: